name: test

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  test:
    uses: stoe/policies/.github/workflows/policy-node-test.yml@main
    permissions:
      contents: read
      packages: read
